name: .NET

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore QuickstartTemplate.sln
      - name: Build
        run: dotnet build QuickstartTemplate.sln --no-restore
      - name: Test
        run: dotnet test QuickstartTemplate.sln --no-build --verbosity normal
